image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS: "25.2.3"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 libqt5widgets5
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/tools_r${ANDROID_SDK_TOOLS}-linux.zip
  - unzip -q android-sdk.zip
  - echo y | tools/android --silent update sdk --no-ui --all --filter android-${ANDROID_COMPILE_SDK}
  - echo y | tools/android --silent update sdk --no-ui --all --filter platform-tools
  - echo y | tools/android --silent update sdk --no-ui --all --filter build-tools-${ANDROID_BUILD_TOOLS}
  - echo y | tools/android --silent update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | tools/android --silent update sdk --no-ui --all --filter extra-google-google_play_services
  - echo y | tools/android --silent update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/
  - export PATH=$PATH:$PWD//platform-tools/
  - chmod +x ./gradlew

stages:
  - build
#  - test

#lintDebug:
#  stage: build
#  script:
#    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

#debugTests:
#  stage: test
#  script:
#    - ./gradlew -Pci --console=plain :app:testDebug
