coverage:
  status:
    project:
      default:
        target: 0% # minimum percent to be considered a success
        threshold: 100% # maximum percent coverage is allowed to drop by
        
    patch:
      default:
        target: 0% # minimum percent to be considered a success
        threshold: 100% # maximum percent coverage is allowed to drop by
        
