name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build dokka documentation with Gradle
        run: |
          ./gradlew dokka
          mv app/build/dokka/app app/build/dokka/docs

      - name: Upload documentation to repo
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          ACCESS_TOKEN: ${{ secrets.DOC_SECRET }}
          REPOSITORY_NAME: Zyviax/345Documentation
          BRANCH: master
          FOLDER: app/build/dokka
          COMMIT_MESSAGE: "updating documentation"
